import { Request, Response, Router } from 'express'
import createDocx from '../utils/generateDocs'
// import { Carta_Compromiso } from '../types/types'

import path from 'path'
import fs from 'fs'

const files = Router()

files.get('/', (req: Request, res: Response) => {
    console.log(req.body);
    res.send('Desde root de files')
})

files.get('/download/:file/:type', async (req: Request, res: Response) => {

    const info = req.body

    console.log(req.body);

    let { file, type } = req.params

    try {
        await createDocx(file, info)
        // Ruta donde se encuentra alojado el archivo que se va a enviar
        const entryFilePath = path.resolve(__dirname, "..", 'templates', 'autogenerated', 'auto_generated.docx');
        console.log(entryFilePath);

        if (type === 'docx') {
            /** Establece headers en caso de mandar un docx */
            res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
            res.setHeader("Content-Disposition", `attachment; filename=${file}.docx`);

            if (!fs.existsSync(entryFilePath)) throw new Error('El archivo docx no existe o no se genero correctamente')

            const docxBuffer = fs.readFileSync(entryFilePath)
            res.status(200).send(docxBuffer)
        }
    } catch (error) {
        console.log(error);
    }
})

export default files